### ISSUE TITLE
[Build bug] UnityEngine assemblies missing on Game Jolt plugin scripts on build

### ISSUE THREAD

**Issue by Tetriser** [InfectedBytes/gj-unity-api#18]
![gjbuildbug](https://user-images.githubusercontent.com/5746458/36460442-4d1dd3aa-16f3-11e8-909f-a6189b4ac68b.PNG)

This happens each time I tried to build the project, the build fails as the compiler fails to find Unity-related namespaces in the wrapper scripts.

Is this a bug or something?

**Comment by InfectedBytes** [comment]
that's very strange.
Unity has sometimes problems with assets in the "Plugins" assembly, so you may have to close Unity and reopen it, that might help. If not, could you please tell me which Unity version you are using?

**Comment by Tetriser** [comment]
Tried today, still the same error.

I'm using Unity 2017.3.0f3.

**Comment by InfectedBytes** [comment]
Seems like one of those "typical Unity bugs". Every now and then unity fails to import a package correctly. If that happens, the best solution seems to "Reimport All Assets" from the menu. Depending on the size of the project, this may take a while (several minutes).

**Comment by Tetriser** [comment]
Tried to do that, but Unity keeps crashing after I do so.

**Comment by InfectedBytes** [comment]
does it really crash or is the reimport just stuck? If the later one, you just have to wait, for example the oculus sdk needs half an hour to reimport and most of the time it seems to be stuck.
You could also try to add the UnityEngine reference manually, but that might be overwritten by unity.
One other solution I found online was to reinstall Unity, but hopefully that isn't necessary.

**Comment by Tetriser** [comment]
It crashed, there's one time that I tried again but the Unity process is dead. (Zero memory, disk or CPU usage, but still there)

**Comment by InfectedBytes** [comment]
That's indeed very strange, maybe you find help in the unity forums. I doubt that you're the only one having this issue with Unity, so someone there might have a solution 😄

**Comment by Tetriser** [comment]
Well, nobody is answering my question in the forums for 2 days now.

**Comment by InfectedBytes** [comment]
I'm sorry for that, I've expected that the Unity forum could help, because this problem is not tied to this asset, but a general problem with Unity's import instabilities. 
What happens if you create a new MonoBehaviour in that location? Does it also mark the usings as errors?
You could also try to delete the folder and reimport it or move the inner folders out of the Plugins folder.
Besides of that I could only recommend the things that I've found on the forums:
[Post 1](https://answers.unity.com/questions/574256/monodevelop-401-wont-recognize-unityengine-namespa.html)
[Post 2](https://answers.unity.com/questions/1235110/the-type-or-namespace-unityengine-could-not-be-fou.html)
[Post 3](https://answers.unity.com/questions/647870/unityengine-could-not-be-found.html)

**Comment by Tetriser** [comment]
I'm closing this issue, it's actually a faulty Unity installation.

Just reinstalled Unity and everything works fine now.

Anyway, thanks for the support.

**Comment by InfectedBytes** [comment]
perfect, I'm glad it worked out 😄
